select *
from AUDIT_UNIFIED_ENABLED_POLICIES;

noaudit policy AUD_UP_DEL_HR_EMPLOYEES
by TOKO_ONLINE, SALES;

begin
    DBMS_AUDIT_MGMT.CLEAN_AUDIT_TRAIL(
            AUDIT_TRAIL_TYPE => DBMS_AUDIT_MGMT.AUDIT_TRAIL_UNIFIED,
            USE_LAST_ARCH_TIMESTAMP => FALSE,
            CONTAINER => DBMS_AUDIT_MGMT.CONTAINER_CURRENT);
end;

select count(*)
from UNIFIED_AUDIT_TRAIL;
