select EMPLOYEE_ID, FIRST_NAME, JOB_ID
from EMPLOYEES
where JOB_ID in ('AC_ACCOUNT', 'HR_REP', 'IT_PROG', 'ST_CLERK');


select EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID
from EMPLOYEES
where DEPARTMENT_ID in (10, 90, 100);
