select EMPLOYEE_ID, FIRST_NAME, MANAGER_ID
from EMPLOYEES
where MANAGER_ID is null;

select EMPLOYEE_ID, FIRST_NAME, COMMISSION_PCT
from EMPLOYEES
where COMMISSION_PCT is null;


select EMPLOYEE_ID, FIRST_NAME
from EMPLOYEES
where EMAIL is null;
