select EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID, MANAGER_ID
from EMPLOYEES
where DEPARTMENT_ID = 90 and MANAGER_ID = 100 and FIRST_NAME like '__e%';

select EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID, MANAGER_ID
from EMPLOYEES
where DEPARTMENT_ID = 90 or MANAGER_ID = 100 ;


select EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID, MANAGER_ID
from EMPLOYEES
where DEPARTMENT_ID = 90 or MANAGER_ID = 100 and FIRST_NAME like '__e%';


select EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID, MANAGER_ID
from EMPLOYEES
where (DEPARTMENT_ID = 90 or MANAGER_ID = 100) and FIRST_NAME like '__e%';
